- .github/workflows/gating.yaml
- pyproject.toml
- tests/unit/models/test_output.py
- tests/unit/package_managers/test_gomod.py
- tox.ini
* set line_length=100 to match black
* run it outside of flake8 to improve the atrocious error messages
> Improve the isort experience

- cachi2/core/errors.py
- cachi2/core/extras/envfile.py
- cachi2/core/models/output.py
- cachi2/interface/cli.py
- tests/unit/extras/test_envfile.py
- tests/unit/test_cli.py
Generates env. vars in the specified format from the output.json in the output directory.
Allows overriding the output directory path in case the user is planning to move the output directory somewhere else.
Also improve error handling in the CLI
> Add generate-env subcommand

- .containerignore
- .github/workflows/gating.yaml
- Containerfile
Only a minimal configuration was set to the Containerfile, we will need to add more dependencies as other package managers are onboarded.
> Add the Containerfile

- .github/workflows/gating.yaml
- tox.ini
Older versions run with unsupported nodejs
Signed-off-by: Martin Basti <mbasti@redhat.com>
> workflow: use checkout action version 3

- README.md
- docs/dependency_confusion.md
CLOUDBLD-11125
More details in commit messages
> Adjust dependency confusion doc for Cachi2

- cachi2/interface/cli.py
Cachi2 runs `go mod tidy` after downloading, not before.
> Fix --force-gomod-tidy help message

- docs/pull_request_template.md
Cachi2 development is being driven by features that are needed by HACBS.
Since the OSBS2 integration is still intended, a Github issue was filed with the intention of keeping track of all changes that are introduced to Cachi2 that will need to be handled in the future integration effort.
We need to check each PR to see if that issue needs to be updated.
> Adds item to the PR checklist aiming to track OSBS2 integration issues

- cachi2/core/errors.py
- cachi2/core/package_managers/gomod.py
- cachi2/core/packages_data.py
- cachi2/core/utils.py
- tests/unit/package_managers/test_gomod.py
Replace existing error classes with the new ones designed in CLOUDBLD-11302
Other parts of error handling changes to follow in separate PRs
Invalid Input is not included yet because nothing would raise it currently
> Implement new error classes

- cachi2/core/errors.py
- cachi2/core/extras/envfile.py
- cachi2/core/package_managers/gomod.py
- cachi2/interface/cli.py
- tests/unit/extras/test_envfile.py
- tests/unit/package_managers/test_gomod.py
- tests/unit/test_cli.py
- tests/unit/test_errors.py
CLOUDBLD-12401
Still missing:
* turn pydantic validation into InvalidInput error
* different retcode for user errors
* log errors before printing them
> Make error messages friendlier

- cachi2/core/errors.py
- cachi2/core/models/input.py
- cachi2/interface/cli.py
- tests/unit/models/test_input.py
- tests/unit/test_cli.py
Main changes:
* re-raise input validation errors as InvalidInput
* return rc=2 for invalid usage
* log errors before printing them (https://github.com/containerbuildsystem/cachi2/pull/20#issuecomment-1308881540)
WIP: how to log multiline errors
> Error updates vol. 3

- cachi2/core/config.py
- cachi2/core/package_managers/gomod.py
- tests/unit/package_managers/test_gomod.py
This option is a tech debt that was inherited from Cachito. The presence of a go.mod file is basic requirement for processing a Go module, which made us decide to remove this option altogether in Cachi2.
This PR also adds a unit test to cover the check that guarantees that the file is always present in the processed paths.
> Remove the ignore_missing_gomod configuration option

- README.md
- docs/pull_request_template.md
Short section in the README + a checklist item to keep links updated
> Document error message guidelines

- tests/unit/package_managers/conftest.py
- tests/unit/package_managers/test_gomod.py
Without the API as we have in Cachito, these tests needed to be pretty much rewritten from scratch. They were broken down into two tests: one that covers the ported "dependency replacements feature" from Cachito, and one that covers the main "fetch gomod source".
> Test fetch gomod source

- tox.ini
whitelist_externals was removed in tox 4
https://tox--2601.org.readthedocs.build/en/2601/faq.html#tox-4-removed-tox-ini-keys
Signed-off-by: Taylor Madore <tmadore@redhat.com>
> use allowlist_externals key in tox.ini

- cachi2/core/__init__.py
- cachi2/core/models/input.py
- cachi2/core/models/output.py
- cachi2/core/models/validators.py
- cachi2/core/package_managers/gomod.py
- cachi2/core/resolver.py
- cachi2/interface/cli.py
- tests/unit/models/test_input.py
- tests/unit/models/test_output.py
- tests/unit/test_cli.py
- tests/unit/test_resolver.py
CLOUDBLD-11105
Add everything needed to support pip except for the `fetch_pip_source` function which would actually do the work
> Support specifiying "pip" packages in the CLI

- cachi2/core/checksum.py
- cachi2/core/package_managers/general.py
- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_general.py
- tests/unit/package_managers/test_pip.py
- tests/unit/test_checksum.py
Clean up the pkg_managers.general module a bit
- N/A [Issue](https://github.com/containerbuildsystem/cachi2/issues/13) that tracks breaking changes to the OSBS2 integration is updated (if applicable)
> Move checksum-related things to their own module

- tests/unit/models/test_input.py
- tests/unit/package_managers/test_pip.py
- tox.ini
- N/A [Issue](https://github.com/containerbuildsystem/cachi2/issues/13) that tracks breaking changes to the OSBS2 integration is updated (if applicable)
> Enable mypy for tests

- Containerfile
This env variable was defaulting to only "direct", which would make the go command to skip the proxy altogether, resulting in very long download times.
Signed-off-by: Bruno Pimentel <bpimente@redhat.com>
> Set GOPROXY in the Containerfile

- Containerfile
- cachi2/core/config.py
- cachi2/core/package_managers/gomod.py
It was previously being set on the image environment, which makes the Python subprocess that is used to call "go mod download" to not pick it up.
> Fix the way the GOPROXY variable is set in Cachi2 

- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
CLOUDBLD-11107
Do not nest them under `deps/pip/{package_name}/`.
We need to have all the PyPI deps in the same directory so that the piprepo library can build a local index for them.
---
*Side note on filename conflicts.*
Filename conflicts should be impossible. Python sdists follow a naming convention (and since [PEP 625](https://peps.python.org/pep-0625/), there is even a standard) that allows the name and version of the project to be determined from the filename.
Cachi2's code already relies on this convention to find the sdist archive for a given name==version.
The only time a filename conflict should be possible (guaranteed, in fact) is in cases like
- FooBar==1.0.0
- foobar==1
These two dependencies are exactly the same per normalization rules, their filenames must be identical …
> Download PyPI dep archives directly to deps/pip/

- cachi2/core/resolver.py
- tests/integration/test_data/gomod_with_deps/output.json
- tests/unit/test_resolver.py
There was a bug where the output returned from resolve_packages could
never contain any environment variables.
The argument to the merge_outputs function is an Iterable. An Iterable
may be consumed by iterating it (generators, iterators). If the
iterable does get consumed while collecting the packages list, the
env_vars list will always be empty.
Fix the issue and update unit tests to catch it in the future.
- N/A New code has type annotations
- N/A [Issue](https://github.com/containerbuildsystem/cachi2/issues/13) that tracks breaking changes to the OSBS2 integration is updated (if applicable)
> Fix how we merge package manager outputs

- Makefile
- README.md
Support local integration testing with Makefile build command
> Add Make build command for integration test

- tox.ini
The log_cli option makes pytest live-log everything: https://docs.pytest.org/en/7.1.x/how-to/logging.html#live-logs
In unit tests, that generates a lot of unwanted noise. Use live logging only for integration tests with --log-cli-level=DEBUG.
Also drop the --capture=no and log_level options, which are no longer needed.
> Don't use live logging in unit tests

- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
CLOUDBLD-11107
We had a weird split where the directory path was generated inline in the _download_X_package functions and the filename was generated by a separate function.
Generate the whole file path in the separate function.
> Refactor external requirement filepath generation

- cachi2/core/config.py
- tests/integration/test_package_managers.py
Test case is supposed to fail without gomod-vendor flags when a repository with vendor directory is provided.
CLOUDBLD-12625
> Add gomod vendored integration test without flags

- .github/workflows/gating.yaml
- .github/workflows/multi-arch-build.yaml
This PR will add ppc64le support to the Cachi2 image.
> Added ppc64le support

- cachi2/core/checksum.py
- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
- tests/unit/test_checksum.py
The current process for verifying the checksums of pip packages with multiple --hash options has some issues:
* Re-calculates checksums for the same algorithm over and over again
* Generates a lot of noise by logging each mismatch separately
* Produces WARNING logs even when nothing is wrong
Rework the hash checking:
* Calculate the checksum for each algorithm at most once
* If any checksum does match, don't log any mismatches
* If none of the checksums match, log one mismatch per algorithm
> Rework how we verify against multiple checksums

- .github/workflows/gating.yaml
- README.md
- cachi2/interface/cli.py
- docs/gomod.md
- docs/usage.md
- hack/test_gomod.sh
- hack/test_pip.sh
- tests/integration/test_package_managers.py
- tests/unit/test_cli.py
To help handling the parameters in Stone Soup pipelines, we need to allow both packages and flags to be set in a single parameter. 
Instead of keeping the current `package` and `flags` parameters, they are being merged into a single Typer argument that will cover both use cases, as follow: 
```
cachi2 fetch-deps gomod
cachi2 fetch-deps '{"type": "gomod"}'
cachi2 fetch-deps '[{"type": "gomod"}, {"type": "pip"}]'
cachi2 fetch-deps '{"packages": [{"type": "gomod"}], "flags": ["gomod-vendor"]}'
cachi2 fetch-deps gomod --gomod-vendor
```
> Allows the CLI to parse packages and flags using a single parameter

- Makefile
- tests/integration/test_package_managers.py
I adjusted Makefile build command to provide always fresh Cachi2 build.
Implemented gomod-vendor-check test cases are supposed to fail due to provided:
* wrong vendor
* empty vendor
CLOUDBLD-12627
> Add Cachi2 gomod-vendor-check test cases

- cachi2/core/models/input.py
- tests/unit/models/test_input.py
- tests/unit/package_managers/test_gomod.py
- tests/unit/package_managers/test_pip.py
Previously, it was possible to successfully call fetch-deps passing a empty list:
```sh
cachi2 fetch-deps "[]"
```
> Require that a request specifies at least one valid package

- tests/integration/test_package_managers.py
expected_rc variable got changed in other PR to expected_exit_code
> Fix refactored variable

- tests/__init__.py
- tests/integration/utils.py
Before: "Expected: {lots_of_JSON}"
After: diff generated by pytest's assert introspection
> Improve errors from asserts in int. test utils

- tests/integration/test_data/pip_e2e_test/container/Containerfile
- tests/integration/test_data/pip_e2e_test/fetch_deps_sha256sums.json
- tests/integration/test_data/pip_e2e_test/output.json
- tests/integration/test_gomod.py
- tests/integration/test_pip.py
- tests/integration/utils.py
Test case checks fetching pip dependencies, generating environment vars file,
injecting project files, building an image with all prepared prerequisites, and testing
if pip packages are present in the built image.
STONEBLD-473
> Add pip e2e integration test

- .github/workflows/gating.yaml
By default, when one job from a `matrix` fails, the others get cancelled. For linters, this is not what you want.
> Don't fail-fast linters

- cachi2/interface/cli.py
- tests/unit/test_cli.py
> STONEBLD-696

- .github/workflows/gating.yaml
- Containerfile
- README.md
- cachi2/core/extras/envfile.py
- pyproject.toml
- tests/integration/test_data/gomod_e2e_test/output.json
- tox.ini
> Update to fedora-37, python-3.11, and go-1.19

- README.md
- docs/usage.md
Just a minor proposal on the newly added docs about the configuration file option in the CLI (follow up to #81). 
I feel like the usage docs should be focused entirely on practical examples, so I propose moving this part to the main README.
Feel free to close this PR if you disagree with the proposal.
> Move configuration docs to the main README file

- tests/integration/test_pip.py
The new revision pins the url of the tested Containerfile, so the expected output will no longer change when we update the parent image in our Containerfile.
- N/A Code coverage from testing does not decrease and new code is covered
- N/A New code has type annotations
> Bump pip-e2e-test repo revision

- cachi2/core/package_managers/gomod.py
- tests/integration/test_data/gomod_e2e_multiple_modules/bom.json
- tests/integration/test_data/gomod_e2e_test/bom.json
- tests/integration/test_data/gomod_vendor_check_correct_vendor/bom.json
- tests/integration/test_data/gomod_vendor_check_no_vendor/bom.json
- tests/integration/test_data/gomod_vendored_with_flag/bom.json
- tests/integration/test_data/gomod_with_deps/bom.json
- tests/unit/package_managers/test_gomod.py
The code currently reports only package deps, not module deps. Report
modules as well.
Simplify the mocking of the fetch_gomod_source test and make sure it tests this case.
> Fix gomod SBOM generation

- cachi2/core/package_managers/pip.py
- pyproject.toml
- requirements-extras.txt
- tests/unit/package_managers/test_pip.py
Involves minor refactoring here and there, but no functional changes.
Also add 'typing-extensions' to dev dependencies so that we can make use of typing features not available in python 3.9 (such as TypeGuard).
> Add type hints to parts of the pip code and tests

- .tekton/pull-request.yaml
- .tekton/push.yaml
- .tekton/tag-latest.yaml
This PR enables image builds through the RHTAP pipeline. The change is meant to leverage the exitisting security scanners that are available in RHTAP, making Cachi2 compliant to the Enterprise Contract policies.
Images will now be pushed to quay.io/redhat-appstudio/cachi2.
The follow up PR, #111, proposes the complete removal of the current multi-arch build pipeline.
> Add Tekton pipeline definitions to enable builds in RHTAP

- tests/unit/package_managers/conftest.py
- tests/unit/package_managers/test_gomod.py
Skip commit hooks when creating fake repos for testing. Some commit
hooks may be quite slow and result in, say, quadrupling the time taken
to run the entire test suite.
> Speed up tests that use `git commit`

- tests/integration/test_npm.py
Extend npm test coverage by adding dependency with @group component
> Add react-dom package to extend npm coverage

- README.md
- cachi2/core/config.py
- cachi2/core/package_managers/general.py
- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_general.py
- tests/unit/package_managers/test_pip.py
https://issues.redhat.com/browse/STONEBLD-941
- N/A New code has type annotations
> toil(bandit): silence request_without_timeout

- .tekton/release.yaml
PipelineRun runs for every tag push in the repository. Image in quay
with commit hash tag is tagged with semantic version.
STONEBLD-471
> Add PipelineRun for release

- .github/workflows/gating.yaml
After building the cachi2 image with buildah, `podman run` somehow stops
working.
```
$ podman run -t cachi2:${{ github.sha }} --version
...
time="2023-05-31T11:24:06Z" level=warning msg="Failed to add conmon to cgroupfs sandbox cgroup: creating cgroup path /libpod_parent/conmon: write /sys/fs/cgroup/cgroup.subtree_control: operation not supported"
Error: OCI runtime error: crun: the requested cgroup controller `pids` is not available
```
This doesn't happen when building the image with podman. It also doesn't
happen when building a different image with buildah. It is the specific
combination of `buildah bud` + the cachi2 Containerfile that somehow
breaks podman afterwards.
Use podman build instead of buildah to avoid this issue.
Note: based on further testing, it seems that buildah …
> Build the cachi2 image in GH actions with podman

- docs/pull_request_template.md
Mypy enforces them after e31c493ac6653338b00a71e87256242fd0fa67c7
> Remove type-annotations PR checklist item

- cachi2/core/package_managers/gomod.py
- cachi2/core/scm.py
- tests/unit/package_managers/test_gomod.py
- tests/unit/test_scm.py
In preparation for the npm (and also pip) purl implementation
This should make it easier to generate purls for the main packages (which should use `vcs_url` qualifiers)
Also use this mechanism for gomod (when getting the repo name for the source dir)
> Implement unified way to generate `vcs_url` for the main package purl

- cachi2/core/models/output.py
- cachi2/core/package_managers/npm.py
- tests/integration/test_data/npm_smoketest_lockfile1/bom.json
- tests/integration/test_data/npm_smoketest_lockfile2/bom.json
- tests/integration/test_data/npm_smoketest_lockfile3/bom.json
- tests/unit/package_managers/test_npm.py
STONEBLD-1112
```
- registry dependencies: pkg:npm/name@version
- git dependencies: pkg:npm/name[@version]?vcs_url=url[#subpath]
- http dependencies: pkg:npm/name[@version]?download_url=url
- file dependencies: treated as git dependencies from the source repo
- main package: treated as a `file:.` dependency
```
> Implement purls for npm packages

- cachi2/core/package_managers/npm.py
- tests/integration/test_npm.py
- tests/unit/package_managers/test_npm.py
Do not download bundled dependencies, do report them in the SBOM.
Use the same purls as registry dependencies. Bundled dependencies should be differentiated in the future via the `cdx:npm:package:bundled` property (outside the purl).
> Fix the handling of npm bundled dependencies

- README.md
> Document releasing

- .tekton/push.yaml
- .tekton/release.yaml
- .tekton/tag-latest.yaml
The GitHub UI does not show on-push Tekton pipelines at all. There's no
way to know when one fails.
Add Slack notifications. When a pipeline fails, it will send a
notification in the Slack channel configured as the "build" team channel
in the RHTAP instance where our pipelines run.
> Add failure notifications to on-push pipelines

- tests/unit/data/sboms/cachi2.bom.json
- tests/unit/data/sboms/merged.bom.json
- tests/unit/data/sboms/syft.bom.json
- tests/unit/test_merge_syft_sbom.py
- tox.ini
- utils/merge_syft_sbom.py
The script performs a deduplication of reported components, favoring Cachi2's report whenever possible:
- Removes any Syft component that has a matching PURL with a Cachi2 component
- Removes Golang locally replaced modules from Syft
- Removes non-registry Pip and NPM dependencies reported by Syft
More details about the deduplication can be found [here](https://github.com/brunoapimentel/rhtap-cachi2-sbom-merge/blob/main/find-duplicates.ipynb).
This script is primarily meant to perform the merging of both SBOMs in the RHTAP build pipeline. The reason to implement it in Cachi2 is because of its growing complexity, which would be rather unmaintanable if written inline in a Tekton yaml file.
- [n/a] Docs links in the code are still valid (if docs were …
> Add utility script to merge Cachi2 and Syft SBOMs

- cachi2/core/package_managers/npm.py
- tests/unit/package_managers/test_npm.py
- https://issues.redhat.com/browse/STONEBLD-1474
Committing node_modules into the repository would allow the user to "vendor" their dependencies, in a way.
The RHTAP build would have no guarantee that the build really used the dependencies that cachi2 prefetched.
The generated SBOM could be inaccurate.
> feat(npm): fail request if 'node_modules' exists

- cachi2/core/package_managers/pip.py
- docs/pip.md
- tests/unit/package_managers/test_pip.py
> Don't fail when we can't determine the project name and version

- tests/integration/test_data/pip_without_metadata/.build-config.json
- tests/integration/test_data/pip_without_metadata/bom.json
- tests/integration/test_data/pip_without_metadata/fetch_deps_sha256sums.json
- tests/integration/test_pip.py
Test case if there no setup files in the repository or cachi2 fails to resolve the name.
JIRA: https://issues.redhat.com/browse/STONEBLD-1181
REPO: https://github.com/cachito-testing/cachito-pip-without-metadata
> Add integration test for handling missing project metadata

- cachi2/interface/cli.py
- tests/unit/test_cli.py
Currently, passing the output directory as a relative path does not work for generate-env and inject-files, because we try to convert a relative path to RootedPath.
ERROR ValueError: path must be absolute: cachi2-output
Fix by resolving the path before converting to RootedPath.
> Fix: allow relative path for helper commands

- .tekton/pull-request.yaml
- .tekton/push.yaml
Recently the RHTAP CI check in the PRs started failing. This is due to some recent changes in the PipelineRun definition in the tekton-ci, where we'd need to specify the bundles inside a resolver format and also specifically mention the kind: Pipeline.
> Fix PaC pipeline reference

- README.md
- docs/npm.md
- docs/usage.md
Add documentation for npm support in `docs/npm.md`
Update `README.md` and `docs/usage.md` files accordingly.
STONEBLD-1110
> Add npm upstream documentation

- pyproject.toml
- requirements-extras.txt
- tests/unit/package_managers/test_general.py
> Add unit tests for asyncio download methods

- cachi2/core/package_managers/gomod.py
- tests/unit/package_managers/test_gomod.py
STONEBLD-1271
Improves the performance of gomod requests when
the number of modules in the repository is large
and/or the git history is extensive. Git tags will only be fetched once per request and the results
are cached in a new ModuleVersionResolver class
> fetch git tags once to resolve go module versions

- tests/integration/test_yarn.py
> cachi2 yarn: test cases

- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
If a user enables `allow_binary option`, reject only those distributions which have no source and no
wheel distributions
STONEBLD-1641
> cachi2 wheels: allow dependencies with only wheel distributions

- tests/unit/package_managers/yarn/test_locators.py
The test parametrization zips the input with the expected output. Zip stops when the shortest iterable ends. That means if the input and output lists have different lengths, cases can be omitted accidentally.
zip(..., strict=True) would solve this on python>=3.10
We support python 3.9, so instead use zip_longest, which will "pad" the shorter list with None
> Make it harder to omit a locator test by mistake

- cachi2/core/errors.py
- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/resolver.py
- cachi2/core/package_managers/yarn/utils.py
- cachi2/core/utils.py
- tests/unit/package_managers/yarn/test_main.py
- tests/unit/test_errors.py
> cachi2 yarn: prefetch dependencies for regular workflow

- cachi2/core/package_managers/yarn/resolver.py
- cachi2/core/utils.py
- hack/mock-unittest-data/yarn.sh
- tests/unit/package_managers/yarn/test_resolver.py
- tests/unit/test_utils.py
STONEBLD-1778
Implement the resolver.resolve_packages function.
Parse the output of `yarn info --all --recursive --cache --json`, pick
out the relevant attributes, post-process them and return them as
Packages.
Alter the Package class slightly:
- make version Optional, use None if yarn info reports 0.0.0-use.local
- make checksum and cache_path both individually Optional, there are
cases where checksum is null but cache_path isn't
- move checksum and cache_path directly to the Package class
- make locator a string (and rename to raw_locator), because parsed
Locators don't make a good identifier for error messages (they omit
unnecessary attributes, so a string representation of a Locator still
wouldn't be grep-able in the yarn.lock file)
- add parsed_locator property
Remove the unnecessary …
> Yarnberry: parse yarn info output

- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/project.py
- tests/unit/package_managers/yarn/test_main.py
- tests/unit/package_managers/yarn/test_project.py
This change depends on https://github.com/containerbuildsystem/cachi2/pull/338
STONEBLD-1776
Since we will rely on corepack to download and configure
the correct version of yarn for a request, ensure that
packageManager is defined in package.json.
Use either yarnPath from .yarnrc, packageManager, or a
combination of the two to set the correct yarn version.
Raise exceptions for the following cases:
- packageManager is already set, but we can't parse it
- neither yarnPath or packageManager is set (or parseable)
- the versions specified by yarnPath and packageManager
are different
> ensure packageManager is correctly set for yarn

- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/project.py
- tests/unit/package_managers/yarn/test_project.py
Implement the classes stablished by the high-level code design (#309) to parse Yarn files (i.e. package.json and yarnrc.yml). 
> Implement classes to parse Yarn files

- Makefile
- README.md
---
- optimizes the `clean` target
- drops the `virtualenv` dependency
- drops the hard 3.9 dependency on the local virtual environments
The last 2 patches are a bit controversial in how they address creation of the virtual environments:
- venv doesn't default to python3.9 anymore because whatever the default python3 on the local system is should do just fine
- force only the `pip-compile` target to Python3.9 as that is kind of a hard dependency that would otherwise potentially cause a regression
I'm open to other suggestions for the ^above as unarguably it's not a particularly nice approach.
> Makefile changes to improve (slightly) local development experience

- cachi2/core/package_managers/gomod.py
- cachi2/core/package_managers/yarn/resolver.py
- cachi2/core/package_managers/yarn/utils.py
- cachi2/core/utils.py
- tests/unit/package_managers/test_gomod.py
- tests/unit/package_managers/yarn/test_utils.py
- tests/unit/test_utils.py
- pass PATH to yarn subprocesses
- use shutil.which to execute commands by abspath
- fix a type annotation
See the commits for more details …
> Subprocess handling improvements

- .github/dependabot.yml
Dependabot opens several PRs almost every day creating noise in the list of PRs. The vast majority of these updates are just patch updates (note the SemVer reference: `major.minor.patch`) which have essentially no impact on this project.
This PR attempts to reduce the noise by grouping pip dependency updates as following:
1. all dependency patch updates in a single PR
2. all dependency minor updates in a single PR
Major updates are left alone so that each major update is a separate PR as major versions often come with backwards compatibility breaking changes.
Grouping updates alone is not going to achieve the goal of reducing the noise without reducing the update schedule to 'weekly' only. 
Now, it's true that by going with weekly updates we open ourselves to the possibility of using …
> Dependabot reduce noise (pip)

- cachi2/core/package_managers/yarn/locators.py
- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/resolver.py
- tests/unit/package_managers/yarn/test_locators.py
- tests/unit/package_managers/yarn/test_resolver.py
STONEBLD-1790
The entries returned by 'yarn info' do not necessarily contain the
correct names and versions of packages.
NAMES:
Yarnberry lets the user specify an arbitrary name whenever the user
adds any dependency other than an npm package or a workspace. The
locator returned by 'yarn info' uses the user-specified name.
VERSIONS:
When reporting local (soft-link, i.e. workspace, portal, link)
packages, 'yarn info' uses '0.0.0-use.local' as the version.
Resolve the actual names and versions of packages from their
package.json files when necessary.
HARD-LINK:
* npm: trust the 'yarn info' data, it seems reliable
* Patch, File, Https: trust the version, resolve the name from the
package.json in the cache archive
* Patch without a cache archive: try to resolve the name of the
original package …
> Yarnberry: resolve package names and versions

- .github/workflows/gating.yaml
This library is a leftover from Cachito and is not necessary for Cachi2. 
This also solves the current problem we are having with the CI.
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/k/krb5/libgssrpc4_1.19.2-2ubuntu0.2_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
```
> Remove libkrb5-dev from Github CI

- cachi2/core/models/input.py
- cachi2/core/resolver.py
- cachi2/interface/cli.py
- tests/unit/models/test_input.py
- tests/unit/test_cli.py
- tests/unit/test_resolver.py
Add a flag which allows for creating requests using a package manager
which is still under development
Any such package manager(s) will be "hidden" behind the new flag, which
should prevent their use by end-users (at least those using Cachi2 in
pipelines)
This story is part of the "Yarn for Node.js" epic
- STONEBLD-1750
Signed-off-by: Ben Alkov <ben.alkov@redhat.com> …
> feat(cli): add 'dev-mode' flag

- tests/unit/package_managers/test_gomod.py
We can't execute the go binary in unit tests as we must expect a basic and completely clean environment for the unit tests. This is not the case with 'test_missing_gomod_file' which transitively calls
run_cmd(["go", "version"], {})
via 'fetch_gomod_source'. …
> tests: unit: gomod: test_missing_gomod_file: Mock run_cmd call

- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/project.py
- tests/unit/package_managers/yarn/test_main.py
- tests/unit/package_managers/yarn/test_project.py
The concept of zero installs is inherently flawed in that one has to either store binary ZIP files or an exploded node-modules dependency tree inside their project repository.  While the former may sound like an acceptable use case from cachi2's hermetic build POV because Yarn provides us with a way to check their integrity, the latter surely doesn't (in fact we refuse projects having node-modules in the repository).
That said, even with the former case some dependencies may specify post-install scripts which will cause such a dependency to be unpacked and expanded under .yarn/cache/unplugged which in simple terms is nothing else than again an expanded node-modules tree which we have to treat the same way as we do for NPM - reject it - because such zero installs would not work without …
> yarn: Forbid zero installs workflow 

- cachi2/core/package_managers/yarn/main.py
- tests/unit/package_managers/yarn/test_main.py
Reasoning:
----------------
- v1 is legacy, doesn't support PnP and hence primitives we rely on for secure dep fetching/checking
- v2 doesn't support the `config` subcommand and `--mode=skip-build` CLI option
- v4 was released only recently with some breaking changes since v3 (support for v4 will be added separately)
[approve-gh-actions]: https://docs.github.com/en/actions/managing-workflow-runs/appr …
> Yarn: check version of Yarn and fail requests for non-v3 binaries

- cachi2/core/package_managers/yarn/main.py
- tests/unit/package_managers/yarn/test_main.py
- tests/unit/package_managers/yarn/test_utils.py
- ~[ ] Docs updated (if applicable)~
- ~[ ] Docs links in the code are still valid (if docs were updated)~
> Yarn: Set 'globalFolder' in override YarnRc && drop _fetch_dependencies helper

- cachi2/core/package_managers/yarn/main.py
- tests/unit/package_managers/yarn/test_main.py
Several yarn settings must be supplied by the cachi2
request output in order for the user to make use of
the prefetched dependencies. These will be supplied by
way of environment variables, which when sourced, will
override any preexisting user configuration in .yarnrc.yml
YARN_GLOBAL_FOLDER must be configured to the deps/yarn
subdirectory of the cachi2 request output directory. This
is the path that cachi2 will populate with the prefetched
dependencies.
YARN_ENABLE_MIRROR must be set to true, otherwise the user
build will not make use of the global cache located at
the globalFolder path that cachi2 prepopulates.
YARN_ENABLE_GLOBAL_CACHE must be set to false, otherwise the
user build will exclusively rely on the cachi2 populated
globalFolder cache rather than copying the dependencies to …
> Add environment variables to yarn request output

- README.md
- cachi2/core/resolver.py
Documentation for the `--dev-package-managers` flag
Signed-off-by: Ben Alkov <ben.alkov@redhat.com>
> docs(dev): '--dev-package-managers' flag

- cachi2/core/package_managers/yarn/main.py
- tests/unit/package_managers/yarn/test_resolver.py
Yarn zero-installs were explicitly forbidden in commit 0a913377ba692ba2e6620bbd8d2b55c16b5b7678, but the commit left some bits referring to zero-installs around. Delete them.
Fixes: 0a913377ba692ba2e6620bbd8d2b55c16b5b7678
I noticed this while looking at #374  …
> tests: unit: yarn: resolver: Drop any zero-install leftovers

- cachi2/core/package_managers/yarn/resolver.py
- tests/unit/package_managers/yarn/test_resolver.py
> cachi2 yarn: purls

- cachi2/core/utils.py
- tests/unit/test_utils.py
Noticed this when investigating https://github.com/containerbuildsystem/cachi2/pull/399#issuecomment-1830949017
When we copy the sources into `./<tmpdir>` we copy `<tmpdir>` (because we created it before the copy actually started) recursively too. By some luck copytree doesn't crash on infinite recursion. Here's a snippet during the the dependecy fetch (in a breakpoint):
```
cachi2-yarn-test.git $ ls -1
app.ts
book-of-armaments
external-packages
my-patches
package.json
packages
README.md
>>>>tmpbhakv792.cachi2-source-copy<<<<
tsconfig.json
yarn.lock
cachi2-yarn-test.git $ cd tmpbhakv792.cachi2-source-copy/
tmpbhakv792.cachi2-source-copy $ ls -1
app.ts
book-of-armaments
external-packages
my-patches
package.json
packages
README.md
>>>>tmpbhakv792.cachi2-source-copy<<<<
tsconfig.json …
```
> util: Fix recursively copying destination directory into itself

- cachi2/core/package_managers/yarn/main.py
Originally introduced by commit a18fda989 to handle erroneous paths during the dependency pre-fetch. However, the handler has always been a NOOP and since we merged b83b621b which always creates a working copy of the input source repository, we don't need any rollback handler at the moment - we can always add it when needed, but until then, let's drop this. …
> package_managers: yarn: Drop the 'undo_changes' handler

- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/resolver.py
While implementing integration test with multiple yarn packages, I came across some bugs.
To reproduce, run integration tests on my local branch: [here](https://github.com/slimreaper35/cachi2/tree/STONEBLD-1899)
[approve-gh-actions]: https://docs.github.com/en/actions/managing-workflow-runs/appr …
> cachi2 yarn: bug fixes

- tests/integration/test_yarn.py
Adding test for a yarn project where a dependency in package.json has been updated but yarn.lock has not been updated. This results in failure in cachi2.
testing repo: https://github.com/cachito-testing/cachi2-yarn-berry/tree/immutable_installs
STONEBLD-1897
> Yarn: add integration test for immutable installs

- tests/integration/test_yarn.py
[test data](https://github.com/cachito-testing/cachi2-yarn-berry/tree/incorrect-checksum) (cachi2-yarn-berry, "incorrect-checksum" branch)
STONEBLD-1895
Signed-off-by: Ben Alkov <ben.alkov@redhat.com> …
> feat(int tests): add "incorrect checksum" scenario

- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/project.py
- tests/unit/package_managers/yarn/test_main.py
Raised during review in a related work: https://github.com/containerbuildsystem/cachi2/pull/425#discussion_r1426765531 …
> Yarn: Add a check for missing lockfile

- README.md
- docs/usage.md
- docs/yarn.md
> docs: Document Yarn support in cachi2

- tests/integration/test_yarn.py
Adding test for a yarn project which is missing a lockfile. This results in failure in cachi2.
STONEBLD-2075 …
> Yarn: add integration test for missing lockfile

- README.md
- cachi2/core/package_managers/gomod.py
> docs: Bump the supported version of Go to 1.21

- tests/unit/data/sboms/merged.bom.json
- tests/unit/data/sboms/syft.bom.json
- tests/unit/test_merge_syft_sbom.py
- utils/merge_syft_sbom.py
There's a new version of the CycloneDX ([1.5](https://cyclonedx.org/docs/1.5/json/)) which introduced changes in the way to specify `.metadata.tools`, and marks the current format as deprecated.
**CycloneDX 1.4:**
```
{
"metadata": {
"tools": [
{
"vendor": "red hat",
"name": "cachi2"
}
]
}
}
```
**CycloneDX 1.5:**
```
{
"metadata": {
"tools": {
"components": [
{
"type": "application",
"author": "red hat",
"name": "cachi2"
}
]
}
}
```
Syft has also adopted the newer format starting from version 0.99.0. This makes the 'merge_syft_sbom.py' script to fail in case a newer Syft SBOM is used. This PR also updates the script so both formats can be handled in Syft SBOMs.
> Update the SBOM merge script to handle the newer metadata.tools format

- tests/unit/package_managers/test_pip.py
I use python3.12 as the default python version on my machine, so the command `make venv` creates a virtual environment with python3.12. For some reason, python3.12 catches a couple of extra linting issues even though the actual version of flake8 is the same. (it was very annoying) …
> fix flake8 errors for everyone who uses python3.12 locally

- .github/dependabot.yml
issue: https://github.com/containerbuildsystem/cachi2/issues/450
> extend dependabot updates schedule interval from weekly to monthly

- .coveragerc
- .github/workflows/gating.yaml
- cachi2/core/rooted_path.py
- pyproject.toml
- tox.ini
> increase cachi2 coverage

- cachi2/interface/cli.py
within user request, we write out json files
(bom.json, .build-config.json) by `model_dump_json()`method, but with no indentation so the output is a huge one-line file
unlike generating data in integration tests:
https://github.com/containerbuildsystem/cachi2/blob/main/tests/integration/utils.py#L228
(as is the [standard for Pipelines as …
> indent JSON files generated by fetch-deps command

- cachi2/core/package_managers/pip.py
PipRequirement had three classmethods with no real connection to the class, so in this commit I'm converting them to staticmethods and passing the necessary data as arguments.
PipRequirement._assess_direct_access_requirement
PipRequirement._adjust_direct_access_requirement
PipRequirement._split_hashes_from_options
Resolves #488 
(as is the [standard for …
> Convert PipRequirement classmethods to staticmethods

- cachi2/interface/cli.py
- tests/unit/test_cli.py
We keep reusing the old output directory hierarchy with repeated fetch runs, overwriting all relevant files. Right now it's all fine because all the files have predictable (pretty much fixed) names, however if we create files/directories with any randomness in their names, we'll be just creating more and more noise with repeated runs. Since we're rewriting all files for the processed package managers anyway (for now), i.e. not reusing data in between runs, it would be better if we first cleaned up the destination if it exists and only then proceed with the fetch.
Note that failing to process a request would be the preferred approach if the output directory existed, because we can't be sure that the existing directory we're being pointed to was indeed created by us so we may end up …
> interface: cli: Remove the top-level output directory before fetching

- docs/gomod.md
v0.6.0 is already out, so we need to document this for the next future release v0.7.0
> docs: gomod: Fix version of cachi2 that introduced full Go 1.21 support

- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
> allow downloading yanked sdists for pip dependencies

- cachi2/core/models/input.py
- cachi2/core/package_managers/rpm/__init__.py
- cachi2/core/package_managers/rpm/main.py
- cachi2/core/package_managers/rpm/redhat.py
- cachi2/core/resolver.py
- cachi2/interface/cli.py
- pyproject.toml
- tests/unit/models/test_input.py
- tests/unit/package_managers/test_rpm.py
- tests/unit/test_cli.py
This is the proof of concept of RPM prefetching functionality.
Design concept: https://github.com/containerbuildsystem/cachi2/discussions/465
A new rpm package manager was added as a development version so `--dev-package-managers` flag needs to be activated.
* `fetch-deps` command will read the rpms lockfile and download listed packages and sources into the output directory structure. Also SBOM file will be generated (bom.json).
* `inject-files` command will create repofile for each arch and create repository metadata out of its RPMs for every repoid dir.
- [approve GitHub Actions workflows][approve-gh-actions] by clicking a …
> Support for prefetching RPMs [PoC]

- tests/integration/test_data/rpm_missing_checksums/.build-config.yaml
- tests/integration/test_data/rpm_missing_checksums/bom.json
- tests/integration/test_rpm.py
This PR introduces 3 integration test scenarios to cover the RPM prefetch functionality:
- Missing checksums
- Invalid checksum
- Invalid file size
For more details on these scenarios, refer to the [design document](https://github.com/containerbuildsystem/cachi2/discussions/516).
The remaining scenarios will be added in a follow up PR.
> RPM PoC: integration tests

- tests/unit/package_managers/yarn/test_main.py
Python 3.12 (not officially supported by cachi2) fails on the
test_main.py::test_set_yarnrc_configuration
unit tests with the following error:
AttributeError: 'called_once' is not a valid assertion. Use a spec
for the mock if 'called_once' is meant to be an attribute.
Indeed, the proper way of handling this assertion is:
mock_obj.assert_called_once()
Relates to:  https://github.com/containerbuildsystem/cachi2/issues/536
- approve the Red Hat …
> tests: unit: package_managers: yarn: Fix mock assert called_once

- cachi2/core/models/input.py
- cachi2/core/models/output.py
- cachi2/core/package_managers/rpm/main.py
- cachi2/core/resolver.py
- cachi2/interface/cli.py
- tests/integration/test_data/rpm_test_repo_file/cachi2.repo
- tests/integration/test_rpm.py
- tests/unit/models/test_input.py
- tests/unit/package_managers/test_rpm.py
Introduce a new input JSON attribute 'options' for the PoC rpm package
manager allowing consumers to pass arbitrary DNF repo configuration
options that would be applied later through the inject-files command.
The general schema for the input JSON is as follows:
```
{
type: <package_manager>
path: <relative_path>
options: {
<namespace>: {
<key1>..<keyN>: Union[str, Any]<val1>
}
}
}
```
which translated to DNF repo options for RPM might then look like:
```
{
type: rpm
path: .
options: {
dnf: {
repoid1: {gpgcheck: 0, deltarpm: 1},
repoid2: {fastestmirro: 1, sslverify: 0}
}
}
}
```
which in turn would end up being dumped to the `.build-config.json` similarly to this:
```
{
"environment_variables": [],
"project_files": [],
"options": {
"rpm": {
"dnf": {
"releases": {
"gpgcheck": 0,
"enabled": …
```
> rpm PoC: Allow specifying DNF options via CLI input JSON 

- .github/workflows/gating.yaml
- Makefile
- README.md
- cachi2/core/package_managers/general.py
- cachi2/core/package_managers/pip.py
- tests/integration/conftest.py
- tests/integration/test_data/pip_custom_index/.build-config.yaml
- tests/integration/test_data/pip_custom_index/bom.json
- tests/integration/test_data/pip_custom_index/fetch_deps_sha256sums.json
- tests/integration/test_pip.py
- tests/integration/utils.py
- tests/pypiserver/package-urls.txt
- tests/pypiserver/start.sh
- tests/unit/package_managers/test_pip.py
- tox.ini
TLDR:
* `--index-url` in requirements.txt is no longer ignored
* If the index url is anything other than https://pypi.org/simple/, report it in the SBOM
* Tell aiohttp not to ignore `.netrc`
* Add way to run local PyPI server that requires auth, add integration test that uses it
Run new test with:
```shell
make test-integration TEST_LOCAL_PYPISERVER=true TOX_ARGS='-k custom_index'
``` …
> Support configurable index urls for pip and private registry auth (not just) for pip

- cachi2/core/scm.py
- tests/unit/test_scm.py
if git origin url contains credentials for
auth, remove them from url so they will not
appear in PURL in SBOM
closes [#521](https://github.com/containerbuildsystem/cachi2/issues/521)
> stop exposing git credentials in SBOM

- tests/integration/test_data/gomod_workspaces/bom.json
In Golang, the tags applied to the repository are used to determine the module's version, and they can be applied individually for submodules (or workspaces).
This commit changes the expected data for the existing gomod workspaces integration test to match the newly pushed tags to the [test repository](https://github.com/cachito-testing/cachi2-gomod/tree/go_workspaces):
```
workspace_modules/echo/v4.2.0
workspace_modules/hello/v1.1.0
workspace_modules/hi/hiii/v1.2.0
```
> Improve the integration tests to cover Go workspace version tags

- docs/pip.md
The main goal is to document the --index-url and to warn users not to put credentials in the url (and point them towards a better way to supply credentials).
Document the other supported options as well for completeness. …
> docs: document supported requirements.txt options

- utils/merge_syft_sbom.py
When Syft scans an image and doesn't find any components, it generates a SBOM without a "components" property (this is valid according to the CycloneDX spec.)
Log file snippet:
```
[merge-cachi2-sbom] Merging contents of sbom-cachi2.json into sbom-cyclonedx.json
[merge-cachi2-sbom] Traceback (most recent call last):
[merge-cachi2-sbom]   File "/src/utils/merge_syft_sbom.py", line 184, in <module>
[merge-cachi2-sbom]     merged_sbom = merge_sboms(args.cachi2_sbom_path, args.syft_sbom_path)
[merge-cachi2-sbom]   File "/src/utils/merge_syft_sbom.py", line 166, in merge_sboms
[merge-cachi2-sbom]     component for component in syft_sbom["components"] if not is_duplicate_component(component)
[merge-cachi2-sbom] KeyError: 'components'
```
**Note:** if the contribution is external (not from an …
> merge_syft_sbom: Handle missing components for the syft sbom

- cachi2/core/package_managers/gomod.py
- tests/unit/package_managers/test_gomod.py
We currently don't allow prerelease version identifiers (e.g. beta/rc, etc.) and commentaries on the version string line (e.g. `go 1.21.0//comment`.
This PR mainly fixes a nasty bug where we fell back to picking an older Go version because of ^this which resulted in a very strange error trying to build buildah from git:
```
2024-05-29 15:48:50,010 INFO Fetching the gomod dependencies at subpath buildah
2024-05-29 15:48:50,011 INFO Fetching the gomod dependencies at the "buildah" directory
2024-05-29 15:48:52,913 INFO go.mod reported versions: '1.20'[go], '-'[toolchain] (cachi2 enforced)
2024-05-29 15:48:52,927 INFO Using Go release: go1.20
2024-05-29 15:48:52,928 INFO Vendoring the gomod dependencies
2024-05-29 15:49:17,954 INFO Retrieving the list of packages
2024-05-29 15:49:23,014 …
```
> Fix our go.mod version string parser regex pattern

- Dockerfile
When commit 49ba69d0 converted the image build to multi-stage it forgot to install the merge_syft_sbom.py utility script that was previously installed as part of copying the whole repo into the image to /src/utils/merge_syft_sbom.py.
This patch takes a bit of a different path by installing the script as a utility binary to a more standardized location.
Fixes: 49ba69d0de05addbca966b683f75f8a71fcbd1c1
Resolves: https://github.com/containerbuildsystem/cachi2/issues/582
- approve the Red Hat Trusted App Pipeline container build by commenting …
> Dockerfile: Inject merge_syft_sbom script to /usr/local/bin

- cachi2/core/package_managers/yarn/resolver.py
- tests/unit/package_managers/conftest.py
- tests/unit/package_managers/test_gomod.py
This PR dabs at fixing the Code QL issues reported under the 'Security' tab. Most (if not all) are false positives anyway, but let's make Code QL happy for a while.
The reported problem with `tar.extractall` will remain even after this PR because Code QL doesn't see past the immediate context at the end of its nose and so it doesn't see that we kinda validated the TAR members before extraction. It probably wants to see us applying the new `filter=` argument, but that's Python 3.12 only material [1] and so we'll have to dismiss that alert manually, besides it's reported against the unit tests so the naive solution proposed here should be good enough to catch test issues early.
[1] https://docs.python.org/3.12/library/tarfile.html#tarfile.TarFile.extractall
**Note:** if the contribution is …
> Code QL fixes reported under the 'Security' tab

- cachi2/core/package_managers/gomod.py
- tests/unit/package_managers/test_gomod.py
This is just very basic support for 1.22 done by a simple version bump (note that the change comes without pre-installing a new version inside the container because that would require more code changes beyond just the Dockerfile). …
> Preliminary support for Go 1.22

- cachi2/interface/cli.py
- docs/usage.md
- tests/unit/data/sboms/cachito_gomod.bom.json
- tests/unit/data/sboms/cachito_gomod_nodeps.bom.json
- tests/unit/test_cli.py
Functionality for merging SBOMs was already present in the codebase, this commit exposes it to a user.
- [-] Docs links in the code are still valid (if docs were updated)
> Adding a new merge-sboms sub-command

- docs/design/bundler.md
> Bundler design document

- .github/workflows/gating.yaml
- README.md
- codecov.yaml
> cachi2 coverage

- cachi2/core/package_managers/gomod.py
- cachi2/core/package_managers/yarn/utils.py
- cachi2/core/scm.py
- cachi2/core/utils.py
- pyproject.toml
- tox.ini
> bandit security corrections

- docs/design/yarn-v1.md
You can see a barebones PoC with just prefetch (No SBOM generation) using the offline mirror here: https://github.com/taylormadore/cachi2/tree/yarn-v1-limited-poc
- [-] Code coverage from testing does not decrease and new code is covered
- [-] Docs updated (if applicable)
- [-] Docs links in the code are still valid (if docs were updated) …
> add design doc for Yarn 1.x support

- README.md
- cachi2/core/package_managers/gomod.py
- tests/unit/package_managers/test_gomod.py
Go 1.23 was released last month [1]. The only notable change on the tooling with essentially no real impact is the introduction of telemetry data gathering which is documented to be opt-in. To stay on the safe side patch 2 disables telemetry explicitly on Go releases which support it.
[1] https://tip.golang.org/doc/go1.23 …
> Introduce support for Go 1.23

- .github/dependabot.yml
See commit 2 for explanation and e.g. https://github.com/containerbuildsystem/cachi2/actions/runs/10655305260/job/29532650464 (one of many regular occurrences in our CI)
> dependabot: Exclude pydantic version updates from the bigger bunch and group it separately

- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
Typing was disabled in PipRequirement due to several small issues left over time, so this PR addresses all of them and re-enables typing on the file .
Resolves #485 
- [-] Docs updated (if applicable)
- [-] Docs links in the code are still valid (if docs were updated) …
> Enable typing on pip

- Dockerfile
- cachi2/core/models/input.py
- cachi2/core/package_managers/bundler/main.py
- cachi2/core/package_managers/bundler/parser.py
- cachi2/core/package_managers/bundler/scripts/lockfile_parser.rb
- tests/unit/package_managers/bundler/test_parser.py
> bundler: parse Gemfile.lock

- .github/workflows/gating.yaml
- tox.ini
The Python container used is a Debian slim image because Alpine uses musl C library which resulted in our createrepo_c depedency to be built from tarball instead of installed from a wheel (those wheels are based on glibc) which naturally failed as the container doesn't have all the deps needed to build createrepo_c.
~~This PR has also been rebased on top of #633 (can be changed) for testing the tox changes in the GH gating CI environment.~~
See the last commit message for more information.
- approve the Red Hat Trusted App Pipeline container build by …
> Update GH actions to run unit tests in a Python container

- cachi2/core/models/input.py
- tests/unit/models/test_input.py
- tests/unit/package_managers/test_rpm.py
This PR is a direct result of #580, more specifically to tackle:
- https://github.com/containerbuildsystem/cachi2/blob/848c8075caa6cde72a2b9338793786b14f1f2cae/cachi2/core/models/input.py#L109
- https://github.com/containerbuildsystem/cachi2/blob/848c8075caa6cde72a2b9338793786b14f1f2cae/cachi2/core/models/input.py#L214
The goal of this PR is make additions of new options models easier than it is today compared to what is needed in #580.
(as is the [standard for …
> Fix extra options model for rpm

- cachi2/core/package_managers/bundler/parser.py
- cachi2/core/package_managers/general.py
- tests/unit/package_managers/bundler/test_parser.py
This change extends GemDependencies with a method
that will download them from their source.
> bundler: Adding Gem downloader

- cachi2/core/package_managers/bundler/parser.py
- tests/common_utils/__init__.py
- tests/unit/package_managers/bundler/test_parser.py
- tests/unit/package_managers/test_general.py
- tests/unit/package_managers/test_gomod.py
- tests/unit/package_managers/test_npm.py
- tests/unit/package_managers/test_pip.py
See the commit msg for details.
> bundler: download git dependencies

- cachi2/core/package_managers/yarn_classic/main.py
- tests/unit/package_managers/yarn_classic/test_main.py
Based on taylormadore/cachi2 [#f19ce5de](https://github.com/taylormadore/cachi2/commit/f19ce5de5ca12f73ce6cc837877d9f3d53edc81a)
- Implements and closes #625
- Adds unit test
Prefetching dependencies for Yarn in Cachi2 will be done using Yarn's offline
mirror feature. When a project is configured to use the offline mirror, Yarn
will store compressed archives in the mirror directory (specified by env var
`YARN_YARN_OFFLINE_MIRROR`) and can install cached project dependencies
from there later without network access.
The offline mirror also has a setting that controls whether it removes package
archives from the mirror directory when they are no longer needed. Cachi2 will
want to disable automatic pruning of the offline mirror (using env var
`YARN_YARN_OFFLINE_MIRROR_PRUNING=false`), since …
> feat(yarnv1): generate build env vars

- docs/usage.md
gomod-vendor has recently been deprecated, however it was still used in usage.md. It was replaced with a not-deprecated flag.
> chore: Update usage.md after flag deprecation

- .tekton/pull-request.yaml
- .tekton/push.yaml
- .tekton/release.yaml
- .tekton/tag-latest.yaml
The quay.io/redhat-appstudio-tekton-catalog namespace is deprecated, migrate to quay.io/konflux-ci.
Note: task bundles in redhat-appstudio-tekton-catalog *will* keep getting updates for the foreseeable future, but pipeline bundles will not. Update both for consistency. …
> Migrate tekton bundle references to new org

- cachi2/core/package_managers/bundler/main.py
- tests/integration/test_bundler.py
- tests/unit/package_managers/bundler/test_main.py
In order for Bundler to build from the content prefetched by Cachi2, we need to set a few configuration parameters. There are several ways of doing this, but the most robust one is to place a local configuration file into processed repository (see docs/design/bundler.md for details).
This commit introduces a fetch step that presets configuraion parameters. …
> bundler: Provide the build configuration

- tests/integration/conftest.py
- tests/integration/test_data/pip_custom_index/bom.json
- tests/integration/test_pip.py
- tests/integration/utils.py
- tests/pypiserver/start.sh
- tox.ini
It's common that "localhost" translates with both IPv4 and IPv6. The simple containerized test PyPI server we use in our CI doesn't listen on IPv6 which may cause unpredictable issues on hosts where IPv6 is enabled and IPv6 would get prioritized by the low level network stack connection primitives. Therefore, use an IP explicitly to avoid any potential issues during pytest run, e.g.:
DEBUG Starting new HTTP connection (1): localhost:8080
DEBUG ('Connection aborted.',
ConnectionResetError(104, 'Connection reset by peer'))
**PR depends on:** https://github.com/cachito-testing/cachi2-pip-custom-index/pull/1
- [approve GitHub …
> tests: Replace "localhost" domain name with the equivalent IPv4 address

- cachi2/core/models/input.py
- cachi2/core/package_managers/generic.py
- cachi2/core/resolver.py
- tests/unit/models/test_input.py
- tests/unit/package_managers/test_generic.py
- tests/unit/test_cli.py
This PR bootstraps the new generic fetcher, so it can be contributed to. Basic structure and tests added.  
> Generic fetcher: Init package manager

- .github/workflows/gating.yaml
- tests/integration/conftest.py
- tox.ini
This PR is effectively just a vol.1 in a series of small refactorings of our GH CI.
This one only takes care of how:
- we run the integration test suite
- we spin up helper services
This PR **does not** tweak how logs are captured from GH workflows, those remain messy and will handled as part of a different work.
[approve-gh-actions]: https://docs.github.com/en/actions/managing-workflow-runs/approvin …
> [GH workflows] Execute the integration test suite directly on the VM runner & run the simple PyPI test server as a service

- tests/integration/test_yarn_classic.py
> yarn: frozen-lockfile integration test

- CONTRIBUTING.md
Added a rule about responding to inline comments in PRs. Sometimes it takes additional effort to ensure that something was addressed. If this rule is present and respected then it would be easier to track PR progress.
Also added a mention of PR rules and developer's guidelines to "How to contribute" section.
[approve-gh-actions]: https://docs.github.com/en/actions/managing-workflow-runs/approving-wor …
> CONTRIBUTING: Adds PR comments handling rule to guideline

- cachi2/core/package_managers/yarn_classic/main.py
- cachi2/core/package_managers/yarn_classic/workspaces.py
- tests/unit/package_managers/yarn_classic/test_main.py
- tests/unit/package_managers/yarn_classic/test_workspaces.py
In Yarn v1.x workspaces metadata is stored outside of yarn.lock in package.json. This commit inroduces functions for workspaces metadata extraction and a dataclass to represent workspaces.
This addresses https://github.com/containerbuildsystem/cachi2/issues/630 …
> Adding Yarn v1.x workspaces metadata extractor

- .github/dependabot.yml
pydantic is designed to be used with a single version of pydantic-core [1] which follows a different release cycle and currently is our nr.1 violator of version updates blocking other dependency version updates to be accepted.
Dependabot, however, currently can't comply with transitive version range constraints, always happily bumping all pip-compile locked versions to the latest one possible anyway, potentially leading to unresolvable requirements.txt files for the pip ecosystem [2] and so even if pydantic adopted a '<=' version constraint it wouldn't help us at all. Therefore, put pydantic-core to the dependabot ignore set and let be freely installed via pip's pydantic resolution based on the ^above.
[1] https://github.com/pydantic/pydantic/discussions/10670
[2] …
> .github: dependabot: Ignore pydantic-core

- tests/integration/utils.py
The logic for skipping integration tests also skipped them when Dockerfile is changed. This commit adds Dockerfile (and Containerfile just in case) to the list of locations that must be tested.
[pac-running-pipeline]: https://pipelinesascode.com/docs/guide/running/#running-the-pip …
> bug: Don't skip integration tests on Dockerfile change

- tests/integration/utils.py
Adding rules to ensure that all integration tests are run when any file with project dependencies is modified.
> testing: Adding rules to run all ITs on dependencies changes

- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/utils.py
- cachi2/core/package_managers/yarn_classic/main.py
- tests/unit/package_managers/yarn/test_main.py
- tests/unit/package_managers/yarn_classic/test_main.py
This commit unifies handling of version info for Yarn and Yarn Classic package managers.
Resolves: https://github.com/containerbuildsystem/cachi2/issues/660
> yarn: Universal utility for Yarn version detection

- CONTRIBUTING.md
2 weeks may be too slow for some ultra-agile, rapid development consumers of this project, often having led to breaking the scheduled pattern and resorting to releases on an ad-hoc basis. Let's shorten the schedule by a week, describing scenarios at which a given release may be at risk.
[approve-gh-actions]: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public …
> CONTRIBUTING: Update the release schedule: Increase cadence by a week

- cachi2/core/models/sbom.py
- cachi2/core/package_managers/generic/main.py
- tests/integration/test_data/generic_e2e/bom.json
- tests/unit/package_managers/test_generic.py
Generic fetcher now generates SBOM components of purl type pkg:generic. It also produces externalReferences of type distribution for each generic component to allow for gating at later time.
[pac-running-pipeline]: https://pipelinesascode.com/docs/guide/running/#running-the-pipeli …
> generic fetcher: Generate SBOM components

- README.md
- docs/usage.md
Add documentation on how to use the generic fetcher and also an ADR to help move out of the experimental phase.
I've tried to follow the CONTRIBUTING.md guidelines, but since I did not see any previous ADR, I just tried to come up with something. Feel free to give more direction on how you want the docs to look like. Thanks! …
> generic fetcher: Add usage docs

- README.md
- cachi2/core/models/input.py
- cachi2/core/package_managers/generic/main.py
- cachi2/core/package_managers/generic/models.py
- cachi2/core/resolver.py
- docs/adr/0001-add-generic-fetcher.md
- docs/usage.md
- tests/integration/test_data/generic_e2e/bom.json
- tests/integration/test_generic.py
- tests/unit/package_managers/test_generic.py
This change includes the generic fetcher ADR which is a necessary step for the feature to be officially supported. Split from #718 
> generic fetcher: Official support with ADR

- README.md
- cachi2/core/package_managers/generic/main.py
- cachi2/core/package_managers/generic/models.py
- docs/generic.md
- tests/integration/test_data/generic_maven_e2e/.build-config.yaml
- tests/integration/test_data/generic_maven_e2e/bom.json
- tests/integration/test_data/generic_maven_e2e/container/Containerfile
- tests/integration/test_data/generic_maven_e2e/fetch_deps_sha256sums.json
- tests/integration/test_generic.py
- tests/unit/package_managers/test_generic.py
Implements Maven artifact support as described in #692
> Generic fetcher maven support

- cachi2/core/package_managers/bundler/main.py
- docs/bundler.md
- tests/integration/test_bundler.py
- tests/integration/test_data/bundler_everything_present/.build-config.yaml
- tests/integration/test_data/bundler_everything_present_except_gemspec/.build-config.yaml
- tests/unit/package_managers/bundler/test_main.py
It turned out that due to a yet unknown change somewhere
in the ecosystem bundler started ignoring instructions
to not access the web during a build when a git dependency
was present.
This change adds a workaround that explicitly forbids
consulting remotes for branches and references and also
pins a path to local repository in a config. …
> Making bundler respect hermetic requirement

- cachi2/core/package_managers/yarn_classic/workspaces.py
> yarn classic workspaces

- tests/integration/test_rpm.py
Unblock integration CI.
Related to: https://github.com/cachito-testing/cachi2-rpm/pull/4
> [CI]: integration: Reference branches instead of hashes in ref in the RPM module

- cachi2/core/errors.py
- cachi2/core/package_managers/gomod.py
- cachi2/core/package_managers/yarn_classic/resolver.py
- cachi2/core/package_managers/yarn_classic/workspaces.py
- cachi2/core/rooted_path.py
- tests/unit/package_managers/test_gomod.py
- tests/unit/package_managers/yarn_classic/test_resolver.py
- tests/unit/package_managers/yarn_classic/test_workspaces.py
> yarn: Update workspace model

- cachi2/core/package_managers/yarn_classic/resolver.py
- cachi2/core/package_managers/yarn_classic/utils.py
- tests/unit/package_managers/yarn_classic/test_resolver.py
- tests/unit/package_managers/yarn_classic/test_utils.py
> yarn: Resolve dev dependencies

- cachi2/core/package_managers/yarn_classic/main.py
- tests/integration/test_yarn_classic.py
- tests/unit/package_managers/yarn_classic/test_main.py
When yarn fetches a URL dependency into the offline mirror, the name of the tarball is used as the name of the tarball in the mirror.
After running `yarn install` command, in a project where are two different URL dependencies have the same name of the tarball, there will be only one tarball in the offline mirror with such name, because the first one gets replaced by the second one.
closes https://github.com/containerbuildsystem/cachi2/issues/634
(as is the …
> yarn: Detect offline mirror collisions

- docs/yarn.md
- docs/yarn_classic.md
This PR introduces user-facing documentation for Yarn Classic.
> yarn-classic: Adding user-facing docs

- cachi2/core/config.py
- cachi2/core/models/input.py
- cachi2/core/package_managers/metayarn.py
- cachi2/core/package_managers/yarn_classic/main.py
- cachi2/core/resolver.py
- cachi2/core/utils.py
- tests/integration/test_yarn_classic.py
- tests/unit/models/test_input.py
- tests/unit/package_managers/test_metayarn.py
- tests/unit/package_managers/yarn_classic/test_main.py
- tests/unit/package_managers/yarn_classic/test_project.py
- tests/unit/test_cli.py
- tests/unit/test_resolver.py
In order to simplify user interface some logic is added to automatically distinguish between supported Yarn versions.
> yarn: Automated Yarn version detector

- cachi2/core/checksum.py
- cachi2/core/package_managers/npm.py
- cachi2/core/package_managers/yarn_classic/main.py
- cachi2/core/package_managers/yarn_classic/resolver.py
- cachi2/core/package_managers/yarn_classic/utils.py
- tests/integration/test_data/yarn_classic_e2e_test/bom.json
- tests/integration/test_data/yarn_classic_e2e_test_multiple_packages/bom.json
- tests/unit/package_managers/yarn_classic/test_main.py
- tests/unit/package_managers/yarn_classic/test_resolver.py
> yarn: SBOM components

- cachi2/core/package_managers/bundler/main.py
- cachi2/core/package_managers/bundler/parser.py
- cachi2/core/package_managers/bundler/scripts/lockfile_parser.rb
- tests/unit/package_managers/bundler/test_parser.py
> bundler git deps fixes

- cachi2/core/package_managers/generic/models.py
- tests/unit/package_managers/test_generic.py
Pydantic formats down URL types as "type casts" in the serialized dictionary [1]. Apparently, that's by design and the docs advises to use custom serializers for given fields [2].
This patch is necessary, because pydantic 2.10.2 changed their behavior when it comes to handling URL types [3] and so once we bump the version we'd hit a test failure requiring us to change the unit test to "cast" some fields as AnyUrl rather than Url. Since these have no place in plain dictionaries, this patch fixes the problem in the correct way by the use of pydantic serializers.
[1] https://github.com/pydantic/pydantic/issues/10998
[2] https://docs.pydantic.dev/latest/api/functional_serializers/#pydantic.functional_serializers.PlainSerializer
[3] https://pydantic.dev/articles/pydantic-v2-10-release#migrate-t …
> package_managers: generic: Use a serializer for URL-typed fields

- CONTRIBUTING.md
> [CONTRIBUTING] Add a note on the 'hack/mock-unittest-data' directory and how to re-generate mock unit test data

- cachi2/core/package_managers/gomod.py
- cachi2/interface/cli.py
- docs/gomod.md
- tests/unit/package_managers/test_gomod.py
This deprecates the `--force-gomod-tidy` CLI option. Since this effort could result in a controversial breaking behaviour the first attempt is somewhat conservative in that it doesn't default to using `go mod tidy` at all and instead ignores this aspect of a misconfigured repository.
Relates to: https://github.com/containerbuildsystem/cachi2/issues/713 …
> [gomod] Deprecate the '--force-gomod-tidy' CLI flag

- README.md
The work was done in commit 1a746952 . Remove the documentation note that we don't support it.
#553 failed to include this change.
> README: Drop the Go workspace vendoring note

- cachi2/core/models/input.py
- cachi2/core/models/property_semantics.py
- cachi2/core/models/sbom.py
- cachi2/core/package_managers/rpm/main.py
- tests/integration/test_data/rpm_summary_is_reported/.build-config.yaml
- tests/integration/test_data/rpm_summary_is_reported/bom.json
- tests/integration/test_rpm.py
- tests/unit/models/test_input.py
- tests/unit/package_managers/test_rpm.py
This change adds an option to include RPM summary in a SBOM.
> Adding optional RPM summary to SBOMs

- noxfile.py
- tests/integration/test_bundler.py
- tests/integration/test_data/generic_maven_e2e/bom.json
- tests/integration/test_data/generic_maven_e2e/fetch_deps_sha256sums.json
- tests/integration/utils.py
> integration tests minor improvements

- cachi2/core/models/output.py
- cachi2/core/models/property_semantics.py
- cachi2/core/models/sbom.py
- cachi2/core/package_managers/metayarn.py
- cachi2/core/package_managers/utils.py
- cachi2/core/resolver.py
- cachi2/core/utils.py
- cachi2/interface/cli.py
- pyproject.toml
- tests/unit/conftest.py
- tests/unit/data/alpine.pretty.json
- tests/unit/data/sboms/cachi2.bom.spdx.json
- tests/unit/data/sboms/merged.bom.spdx.json
- tests/unit/data/sboms/syft.bom.spdx.json
- tests/unit/data/something.more.simple.0.100.0.spdx.pretty.json
- tests/unit/data/something.simple0.100.0.spdx.pretty.json
- tests/unit/models/test_property_semantics.py
- tests/unit/models/test_sbom.py
- tests/unit/test_cli.py
- tests/unit/test_merge_spdx.py
Support for SPDX format was added to fetch-depds command and also to merge_syft_sboms.
No changes were made in particular package manager generating components which are then converted to cyclonedx format. SPDX sbom can be obtained by calling Sbom.to_spdx().
New switch sbom-type was added to merge_syfy_sboms, so user can choose which output format should be generated - default is cyclonedx. Once all tooling is ready to consume spdx sboms, cutoff changes in this repository can be started.
- approve the Red Hat Trusted App Pipeline container build by …
> Add SPDX format support for SBOM

- cachi2/core/resolver.py
- tests/unit/test_resolver.py
To avoid unintended source code modifications, Cachi2 makes a copy of the source directory when some package managers are used (currently, it's being done just for yarn).
This creates a problem with project files, since the absolute path of files now is pointing to the temporary working copy. The solution introced by this patch reverts these paths back to the original source dir path.
This is intended to be a quick fix, and should only be kept until we solve #712.
Resolves #785.
> Fix project files absolute paths when a work copy is used

- Dockerfile
Although not strictly a direct dependency, it's a convenient tool to have in the image to construct input JSONs for our CLI from within Bash. The total install size is ~1MB so nothing tragically affecting the resulting image size. …
> Dockerfile: Add jq dependency

- cachi2/core/models/sbom.py
- cachi2/core/package_managers/yarn/locators.py
- cachi2/core/package_managers/yarn/resolver.py
- tests/integration/test_data/yarn_e2e_test/bom.json
- tests/integration/test_data/yarn_v4/bom.json
- tests/unit/package_managers/test_generic.py
- tests/unit/package_managers/yarn/test_locators.py
- tests/unit/package_managers/yarn/test_resolver.py
Yarn has a `patch` protocol for the [package patching feature](https://yarnpkg.com/features/patching). Patches should not be reported as independent Components in the SBOM, but should instead be reported as [pedigree](https://cyclonedx.org/docs/1.4/json/#components_items_pedigree_patches) for the patched "regular" package Component. …
> Report Yarn v3/v4 patches as pedigree rather than components

- cachi2/core/models/sbom.py
- tests/unit/models/test_sbom.py
See commit messages for details
> SPDX: make SPDXIDs pass validation + cosmetic improvement

- tests/integration/conftest.py
- tests/integration/utils.py
- tests/unit/conftest.py
- tests/unit/models/test_sbom.py
- tests/unit/test_scm.py
The PR adds several retries to functions which tend to sporadically fail locally for no good reason.
It also addresses several warnings which pollute UTs output. It does not handle
`coroutine 'AsyncMockMixin._execute_mock_call' was never awaited` which is very annoying, but has to be chased with specially trained dogs. …
> Some changes to make local IT runs more stable

- tests/integration/conftest.py
When the -k option is used to select tests by keyword, the existing logic would still skip some tests. This prevents users from running specific tests that are normally skipped. The check ensures that test filtering is bypassed when a keyword is provided. …
> Skip test filtering when using pytest -k option

- tests/integration/utils.py
A couple of small fixes that either fix a regression after the IT test suite repo consolidation or that have bothered me for a while.
> [tests] Integration test fixes

- CONTRIBUTING.md
- README.md
> README.md and CONTRIBUTING.md minor improvements

- README.md
- cachi2/core/package_managers/gomod.py
Go 1.24 has recently been [released](https://tip.golang.org/doc/go1.24). See the commit for more information.
> [gomod] Bump the max supported version to 1.24

- cachi2/core/package_managers/generic/models.py
When a checksum did not match expectations the original implementation would not provide any clues other than stating that something did not match. This change adds the actual mismatching value to the output to help with finding lock file issues. …
> generic: Add a more descriptive error message

- cachi2/core/models/sbom.py
- pyproject.toml
- tests/unit/test_merge_spdx.py
E731 - Do not assign a lambda expression, use a def
We have a bunch of occurrences already and seems like this convenience helper pattern is to stay. Rather than putting #noqa directives everywhere let's just ignore the rule globally. …
> [flake8] Add E731 to the ignored rules

- cachi2/core/package_managers/metayarn.py
- cachi2/core/package_managers/yarn_classic/main.py
- cachi2/core/package_managers/yarn_classic/project.py
- tests/unit/package_managers/yarn_classic/test_main.py
- tests/unit/package_managers/yarn_classic/test_project.py
> yarn improvements

- README.md
- docs/cargo.md
> Add user documentation for cargo package manager

- docs/design/cargo-support.md
A design doc for implementing Cargo support. It mostly follows the general principle for other package managers. The bigger issue of having Rust-based dependencies is described in an appendix since this is not strictly Rust support.
Corresponding repository for ITs is https://github.com/cachito-testing/cachi2-rust
> Cargo design doc

- .containerignore
- .git_archival.txt
- .gitattributes
- MANIFEST.in
- pyproject.toml
This is an attempt to fix one version-related aspect of our container image builds. The last 2 patches are a bit controversial, so I'd be inclined to drop them if requested, but they fix a legitimate workflow issue.
See the patch descriptions for detailed info.
FWIW I used a dummy release on my fork to experiment with this, please give it a try: https://github.com/eskultety/cachi2/releases/tag/1.2.3-alpha
(as is the [standard for Pipelines as …
> setuptools-scm fixes

- .containerignore
The container build from git worktrees will still fail because of the missing MANIFEST.in file in the container build environment.
Fixes: d6a16c214b8370d08746d46619b0844239777ad1
> .containerignore: Exclude MANIFEST.in

- README.md
- cachi2/core/package_managers/bundler/main.py
- cachi2/core/package_managers/gomod.py
- cachi2/core/package_managers/pip.py
- cachi2/core/resolver.py
- docs/adr/0002-yarn-v4.md
- docs/dependency_confusion.md
- docs/design/bundler.md
- docs/design/yarn-v1.md
- docs/usage.md
- tests/unit/data/sboms/cachi2.bom.json
- tests/unit/data/sboms/cachi2.bom.spdx.json
- tests/unit/data/sboms/merged.bom.spdx.json
The project moved to a new GitHub organization "hermetoproject". Change the references accordingly.
> [reorg] Replace mentions of the old containerbuildsystem

- README.md
- cachi2/interface/cli.py
- tests/unit/conftest.py
- tests/unit/extras/test_envfile.py
- tests/unit/models/test_property_semantics.py
- tests/unit/models/test_sbom.py
- tests/unit/package_managers/test_pip.py
- tests/unit/test_cli.py
- tests/unit/test_resolver.py
- tests/unit/test_scm.py
First round of rebranding related changes:
- small but unnoticeable fixes that otherwise impact the rebranding process
- put a rebranding notice in the main README for the time being
> [Rebranding] vol.1 : A tiny prelude

- noxfile.py
It can happen that the nox's session doesn't define the variable leading to:
File "<repo>/noxfile.py", line 150, in pip_compile
PWD = session.env["PWD"]
~~~~~~~~~~~^^^^^^^
KeyError: 'PWD'
The exact circumstances are unknown, but it happened on a git worktree. In any case os.environ should be more stable because that corresponds to the shell's env directly. …
> noxfile: Query PWD from os.environ instead of nox session

- Dockerfile
- tests/integration/utils.py
This is mainly about commit 140881e42fd29cecc872407bf5d07328612a6305 which prioritized storage considerations and  a clean overview (due to the dangling images being opaque) over efficiency which, in hindsight, was a **detrimental** decision wrt integration test suite performance. On its own though we'd still not follow best practices when it comes to layer caching and so additional patches are added on top. All patches combined resulted in decreasing a single e2e test execution (`yarn_e2e_test_multiple_packages` was used) from 86s -> 18s (>4x speedup) on my machine using the `throughput-performance` tuned profile.
We could still squeeze some more out of it by doing a similar thing for the test application image builds (which are still removed at the end of the run) with …
> Containerfile: Maximize layer caching

- cachi2/core/package_managers/yarn_classic/workspaces.py
> yarn: Filter directories in workspace glob resolution

- noxfile.py
The upstream CI fails with:
ERROR: In --require-hashes mode, all requirements must have their
versions pinned with ==. These do not: coverage[toml]>=7.5
By default, pip tries to resolve transitive dependencies of packages when reading the requirements files. Well, that fails if the 'require-hashes' mode is ON. In case one uses a fully resolved and pinned requirements file (we do), pip shouldn't need to spend time trying to re-resolve something that's already resolved, it should use it directly.
> [CI] noxfile: Use --no-deps with pip requirements installation

- cachi2/core/errors.py
- cachi2/core/rooted_path.py
- tests/unit/package_managers/test_generic.py
- tests/unit/package_managers/test_gomod.py
- tests/unit/package_managers/test_pip.py
- tests/unit/test_rooted_path.py
Updated the exception message in the `re_root` function for the `PathOutsideRoot` error to be clearer and more user-friendly. Also, modified the unit tests to check just for the `PathOutsideRoot` error without relying on the exact message matching.
Closes https://github.com/hermetoproject/cachi2/issues/759
[approve-gh-actions]: https://docs.github.com/en/actions/managing-workflow-runs/approving-workf …
> Fix: exception message inside rooted_path.py and unit tests

- docs/usage.md
It was stated in the docs that generic fetcher must be used with '--dev-package-managers' flag which is not correct anymore. This patch removes this statement.
> docs: generic: Update outdated statement

- README.md
- docs/usage.md
Updated the fetch-deps examples to include the --sbom-output-type flag.
Closes https://github.com/hermetoproject/cachi2/issues/812
> docs: update fetch-deps usage example to include --sbom-output-type flag

- hermeto/core/utils.py
> Ensure clean destination dir when fast copy fails

- hermeto/core/package_managers/gomod.py
This is very useful when troubleshooting these types of errors. Currently, the only printed output is this:
```
Error: FetchError: Failed to fetch the tags on the Git repository [...]
```
Which hides the underlying cause.
> gomod: Print the Git error message a failure to fetch tags happens

- README.md
This reverts commit ee2da42510f2706000350668151132444c68b7a3.
With the rebranding effort now complete [1], we can drop the rebranding notice from the main README.
[1] https://github.com/orgs/hermetoproject/discussions/872
> Revert "Rebranding: README.md: Turn on rebranding notice."

- hermeto/core/scm.py
- tests/unit/test_scm.py
Closes: https://github.com/hermetoproject/hermeto/issues/653
> Add a check for invalid path in get_repo_id function

- docs/cargo.md
> docs: Clarify .cargo/config.toml setup

- .github/workflows/gating.yaml
- pyproject.toml
Python 3.13 has been out for a while, but we couldn't easily integrate with it in our CI due to `createrepo_c` which we depend on is slow with releases and didn't provide a 3.13 wheel (we'd have to build it from scratch in our CI). That has recently changed and there is a 3.13 build available -> enable support for 3.13 and test with it in unit tests.
> Add Python3.13 to our supported platforms list

- README.md
- docs/index.md
- mkdocs.yml
> Link README.md to the index page on the website

- hermeto/core/package_managers/yarn_classic/main.py
- tests/unit/package_managers/yarn_classic/test_main.py
> increase yarn 1.x network timeout to 10 min

- hermeto/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
Previously pip would download and process Rust sources even when a user requested just binaries. This change introduces a check to skip Rust sources processing when a user is fine with having just binaries. …
> chore: Make pip skip Rust sources when binaries allowed

- docs/pip.md
- hermeto/core/package_managers/cargo/main.py
- tests/unit/package_managers/test_pip.py
When a Cargo.lock and Cargo.toml do not match `cargo vendor --locked` will refuse to proceed. This is a corner case which manifests itself in several Python packages extended with Rust. While making sure that locks match to configs is not a direct responsibility of Hermeto the messaging around this specific failure was confusing.
This change adds a dedicated exception class to raise when there is a mismatch which contains a more thorough explanation of the problem.
Adds visibility to https://github.com/hermetoproject/hermeto/issues/925
- approve the …
> chore: Improve messaging for corrupt Cargo.locks

- README.md
- hermeto/core/models/input.py
- hermeto/interface/cli.py
- tests/unit/models/test_input.py
- tests/unit/test_cli.py
Closes: https://github.com/hermetoproject/hermeto/issues/934
> cli: Add global mode option for input validation strictness

- docs/usage.md
This commit adds an explanation of the importance of git metadata to Hermeto and a also adds an example of how sources without metadata could be amended to be processed with Hermeto.
Related to: https://github.com/hermetoproject/hermeto/issues/855 …
> docs: Add explanation of git metadata role

- hermeto/core/package_managers/yarn/utils.py
- tests/unit/package_managers/yarn/test_main.py
Unless yarnPath is ignored, it is possible to execute an arbitrary binary when we check that the corepack downloaded yarn version is as expected.
> ignore yarnPath for yarn v2+ during version check

- hermeto/core/config.py
- hermeto/core/package_managers/pip.py
Some users reported a desire to NOT process Rust dependencies automatically. This change introduces a flag to let them do that.
> pip: Add a flag to ignore Rust dependencies

- mkdocs.yml
Some of the docs use footnotes, which the GitHub renderer supports natively [1].
MkDocs requires an extension to handle footnotes [2], enable this extension.
[1]: https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/
[2]: https://squidfunk.github.io/mkdocs-material/reference/footnotes/
[approve-gh-actions]: https://docs.github.com/en/actions/managing-workflow-runs/appro …
> docs: enable footnotes extension in mkdocs

- README.md
- hermeto/core/models/input.py
- hermeto/core/package_managers/gomod.py
- hermeto/interface/logging.py
- tests/integration/test_gomod.py
- tests/integration/utils.py
- tests/unit/package_managers/test_gomod.py
Resolves: https://github.com/hermetoproject/hermeto/issues/933
> [gomod] Apply the permissive setting on go vendor directory integrity checks

- hermeto/core/scm.py
This addresses the following pytest warning under Python 3.13 I noticed by accident:
DeprecationWarning: 'count' is passed as positional argument
parts[-1] = re.sub(r":/*", "/", parts[-1], 1)
This warning is a result of change [1] in cpython, presumably to counter common passing argument mistake by misplacing flags to various re calls [2]. Based on [1] several other keyword arguments are to be converted to keyword-only arguments in the future anyway, so we might need more changes just like this one in the future.
[1] https://github.com/python/cpython/commit/882cb79afa2cb11b180ef699fd5cf038e72f6c85
[2] https://github.com/python/cpython/issues/99918#issuecomment-1333377637
pipeline will not run …
> core: scm: Specify the keyword 'count' in our re.sub call

- noxfile.py
If one passes additional positional arguments via --, e.g.
```
$ nox -s python-3.12 -- tests/unit/package_manager/foo OR
$ nox -s python-3.13 -- -k 'filter'
```
pytest's coverage module is all confused because apparently pytest configures it using the number of all tests collected rather than having it based on the filtered set (which would probably cause other issues) and so the coverage report fails with a returncode of 1. In manual mode you can ignore this, but in automated test runs, e.g. with git bisect this would always return failure and hence a "bad commit".
Fix this by only enabling coverage when no positional arguments were detected on the CLI.
> noxfile: Enable pytest's coverage conditionally

- hermeto/core/package_managers/pip/rust.py
- tests/integration/conftest.py
- tests/integration/test_pip.py
Looks like d78fb42 fix accidentaly removed the heuristic for selecting the proper Cargo.toml when multiple files are present.
This commit simply reintroduces the same heuristic.
Closes #1039 .
Depends on https://github.com/hermetoproject/integration-tests/pull/25 …
> pip: re-introduce heuristic for Cargo.toml detection

- requirements-build.txt
The setuptools-scm library is needed as a dependency when building the project. The lack of this dependency will make the build fail in a hermetic environment.
> Add requirements-build.txt file

- hermeto/core/package_managers/pip/rust.py
- tests/unit/package_managers/pip/test_rust.py
Heuristic for resolving Cargo root directory was reintroduced recently (https://github.com/hermetoproject/hermeto/pull/1040). Unfortunately the problem that it was solving turned out to be system-dependent and thus not directly testable with an integration test. Since this heuristic has once been replaced during refactoring there must be some test that guards against future regressions. This change pulls heuristic into a separate function and covers that function with unit tests to warn future maintainers about possible regressions.
- approve the Red …
> pip: chore: Move Cargo root resolution into a separate function

- docs/bundler.md
- docs/gomod.md
- docs/pip.md
mkdocs-material -- for reference links, renders them incorrectly/styles them weirdly:
- when the name contains *any* formatting (like [`--find-links`][] or even [**--find-links**][]), is rendered as text only (not as links)
- even after tweaking CSS, e.g. [`--find-links`][] is now not only **not** a link, but is styled as all-small-caps O_o
The only fix I could find (with Claude's help), was in-lining the links.
(as is the [standard for Pipelines as …
> Toil(docs): fix broken `pre` links in Pip.md

- .github/workflows/gating.yaml
- noxfile.py
Each linter invocation installs the whole requirements-extras.txt file which results in 1.5G of disk space for just individual nox linter sessions.
$ du -h -d1 .nox
294M .nox/bandit
313M .nox/mypy
294M .nox/flake8
294M .nox/isort
294M .nox/black
1.5G .nox/
I explored the possibility of not installing the full requirements-extras.txt file, but the problem is our resolved and locked requirements file would lose its meaning as we'd always be installing the latest (any) package from pypi. Additionally, the current code transcript relying on a single file is much cleaner than enumerating individual dependencies for a session, so keeping the current approach is better.
The linters take only a few seconds when reusing the virtual environment (pre-existing), so there's no loss in running all …
> noxfile: Group linters and static analyzers to a single session - lint

- hermeto/core/package_managers/gomod.py
- hermeto/core/utils.py
- tests/unit/package_managers/test_gomod.py
I recently adopted some new global git configuration which happened to break some of our unit tests. While the tests in question definitely deserve changes not to be so tightly coupled to an exact git output, we should also not let git pick up user configuration automatically if we want to keep consuming its output and process it further in our logic. …
> [git] Force an empty git config upon git command executions within a repository

- .containerignore
The Konflux build pipeline that we currently use assumes that this file is included. Include it temporarily until a fix is implemented in the build pipeline.
> .containerignore: temporarily include labels.json

- hermeto/core/binary_filters.py
- hermeto/core/models/input.py
- hermeto/core/package_managers/bundler/main.py
- hermeto/core/package_managers/pip/main.py
- tests/unit/models/test_input.py
This PR introduces flexible binary package filtering input parameters that allow users to specify which platform-specific packages to prefetch based on architecture, OS, Python version, and other characteristics.
This is **only** the input model implementation and does not change the current behavior. New behavior for the individual package manager backends will be added in subsequent PRs. …
> Enable platform-specific binary package filtering input

- .tekton/release.yaml
We don't want PaC to fetch the git-clone task from Tekton Hub and inline it. We want to use the git-clone task we specified.
> remove Tekton Hub git-clone annotation

- .tekton/release.yaml
Follow-up to #1086 
https://github.com/konflux-ci/build-definitions/blob/5a0b1b741978687aab7cb99b335b8dbb63dbec82/task/git-clone/0.1/README.md?plain=1#L15
> release: use source subdir from git-clone task

- tests/integration/test_data/gomod_correct_vendor_in_submodule_passes_vendor_check/bom.json
The CycloneDX spec was bumped to 1.6 in 58afb1c, which was missed in 5eb127a
> bump cyclonedx spec for gomod vendor in submodule integration test

- tests/unit/package_managers/test_gomod.py
Fixes missing rebase in https://github.com/hermetoproject/hermeto/pull/1084. While the CI was green, in the meantime, another PR was merged without applying neccessary changes that make ruff unhappy right now. …
> ruff: Remove blank line

- hermeto/core/package_managers/pip/main.py
- hermeto/core/package_managers/pip/package_distributions.py
- hermeto/core/package_managers/pip/requirements.py
- tests/unit/package_managers/pip/test_main.py
- tests/unit/package_managers/pip/test_package_distributions.py
- tests/unit/package_managers/pip/test_requirements.py
> pip: Prepare for binary filters support
