hermetoproject/hermeto

- .github/workflows/gating.yaml
Project changed default branch from master to main
Signed-off-by: Martin Basti <mbasti@redhat.com>
> workflow: fix branch

- README.md
- docs/gomod.md
- docs/usage.md
CLOUDBLD-11125
* High-level overview in the README
* Details in a dedicated doc
* How to specify gomod --package(s)
* How to use the fetched deps
* Available flags
* Vendoring
* gomod, go-package and stdlib dependencies
> Document details of gomod support

- .github/workflows/gating.yaml
> Add container build to CI/CD

- cachi2/core/models/output.py
- cachi2/core/package_managers/gomod.py
- cachi2/core/package_managers/pip.py
- cachi2/core/resolver.py
- cachi2/interface/cli.py
- hack/test_pip.sh
- tests/integration/test_data/gomod_vendor_check_correct_vendor/output.json
- tests/integration/test_data/gomod_vendor_check_no_vendor/output.json
- tests/integration/test_data/gomod_vendored_with_flag/output.json
- tests/integration/test_data/gomod_with_deps/output.json
- tests/integration/test_data/gomod_without_deps/output.json
- tests/unit/extras/test_envfile.py
- tests/unit/models/test_output.py
- tests/unit/package_managers/test_gomod.py
- tests/unit/package_managers/test_pip.py
- tests/unit/test_cli.py
- tests/unit/test_resolver.py
CLOUDBLD-11107
CLOUDBLD-11108
CLOUDBLD-12514
> Make pip support functional

- cachi2/core/package_managers/pip.py
- cachi2/interface/cli.py
- tests/unit/package_managers/test_pip.py
PTAL, just fixing some tiny details
> Minor fixes for pip

- docs/pip.md
- docs/usage.md
* Document the inject-files command
* Add full usage example for pip
- N/A Code coverage from testing does not decrease and new code is covered
- N/A New code has type annotations
> Document pip usage

- README.md
- docs/usage.md
JIRA: CLOUDBLD-11126
Signed-off-by: ejegrova <ejegrova@redhat.com>
> Document configuration parameters

- tests/integration/test_data/gomod_vendor_check_correct_vendor/vendor_sha256sums.json
- tests/integration/test_data/gomod_vendor_check_no_vendor/vendor_sha256sums.json
- tests/integration/test_data/gomod_vendored_with_flag/vendor_sha256sums.json
- tests/integration/test_gomod.py
- tests/integration/test_pip.py
- tests/integration/utils.py
> STONEBLD-697

- cachi2/core/package_managers/gomod.py
- tests/unit/package_managers/test_gomod.py
STONEBLD-631
Adding this flag to the go-list command prevents
erroneous packages from being printed to stderr
and causing fetch-deps to fail needlessly
> add -e flag to go-list command

- cachi2/core/package_managers/gomod.py
- tests/integration/test_data/gomod_e2e_multiple_modules/fetch_deps_file_contents.yaml
- tests/integration/test_data/gomod_e2e_multiple_modules/fetch_deps_sha256sums.json
- tests/unit/package_managers/test_gomod.py
> let Go merge downloaded deps instead of doing it in Python

- .containerignore
- Makefile
- README.md
- tests/integration/conftest.py
- tests/integration/utils.py
- tox.ini
> Improve testing experience

- cachi2/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
> Handle file paths safely for pip

- cachi2/core/models/output.py
- cachi2/core/package_managers/gomod.py
- cachi2/core/rooted_path.py
- pyproject.toml
- requirements.txt
- tests/integration/test_data/gomod_e2e_multiple_modules/bom.json
- tests/integration/test_data/gomod_e2e_test/bom.json
- tests/integration/test_data/gomod_go_generate_imported/bom.json
- tests/integration/test_data/gomod_local_deps/bom.json
- tests/integration/test_data/gomod_vendor_check_correct_vendor/bom.json
- tests/integration/test_data/gomod_vendor_check_no_vendor/bom.json
- tests/integration/test_data/gomod_vendored_with_flag/bom.json
- tests/integration/test_data/gomod_with_deps/bom.json
- tests/integration/test_data/gomod_without_deps/bom.json
- tests/unit/data/gomod-mocks/expected-results/resolve_gomod.json
- tests/unit/data/gomod-mocks/expected-results/resolve_gomod_vendored.json
- tests/unit/package_managers/test_gomod.py
The generate SBOM components are expected to follow this pattern:
```
require github.com/org/repo/module v1.0.0
```
```json
{
"name": "github.com/org/repo/module",
"version": "v1.0.0",
"purl": "pkg:golang/github.com/org/repo/module@v1.0.0?type=module"
}
```
Will use the replaced module's name and version, the original ones are omitted entirely.
```
replace github.com/any-org/any-repo/original-module => github.com/org/repo/replaced-module v1.0.0
```
```json
{
"name": "github.com/org/repo/replaced-module",
"version": "v1.0.0",
"purl": "pkg:golang/github.com/org/repo/replaced-module@v1.0.0?type=module"
}
```
The purl will be based on the repository's remote origin and the version will be resolved from the repository's tags. 
In case the module's name does not match the purl (as in case of a …
> Generate PURLs for Go

- cachi2/core/package_managers/pip.py
- docs/pip.md
- pyproject.toml
- requirements.txt
- tests/unit/package_managers/test_pip.py
> Support pyproject.toml files for pip projects

- docs/usage.md
Restructuring
* Give an overview of the flow
* Go through a gomod example
* Go through a pip example
Also included in the changes are specific call-outs to the dirty git environments when injecting project files.
> rewrite usage documentation

- cachi2/core/models/output.py
- cachi2/core/package_managers/pip.py
- tests/integration/test_data/pip_e2e_test/bom.json
- tests/integration/test_data/pip_multiple/bom.json
- tests/integration/test_data/pip_with_deps/bom.json
- tests/integration/test_data/pip_without_deps/bom.json
- tests/unit/models/test_output.py
- tests/unit/package_managers/test_pip.py
- tests/unit/test_resolver.py
Main package: pkg:pypi/{name}?vcs_url={git_url}@{ref}#{path/to/package}
Pypi dependency: pkg:pypi/{name}@{version}
Git dependency: pkg:pypi/{name}?vcs_url={git_url}@{ref}
Https dependency: pkg:pypi/{name}?download_url={file_url}&checksum={checksum}
STONEBLD-1223
> Generate purls for pip

- tests/integration/test_data/npm_lockfile3_dev_optional_peer_deps/.build-config.yaml
- tests/integration/test_data/npm_lockfile3_dev_optional_peer_deps/bom.json
- tests/integration/test_data/npm_lockfile3_dev_optional_peer_deps/container/Containerfile
- tests/integration/test_data/npm_lockfile3_dev_optional_peer_deps/fetch_deps_sha256sums.json
- tests/integration/test_npm.py
> Add integration test for npm dev, optional and peer dependencies

- cachi2/core/package_managers/npm.py
- tests/unit/package_managers/test_npm.py
Cachi2 will not support End of life package-lock v1 (npm v6).
JIRA: STONEBLD-1558
> Remove code for npm lockfile v1

- cachi2/core/models/output.py
- cachi2/core/package_managers/npm.py
- tests/integration/test_data/npm_bundled_lockfile3/bom.json
- tests/integration/test_data/npm_lockfile3_dev_optional_peer_deps/bom.json
- tests/integration/test_data/npm_lockfile3_multiple_dep_versions/bom.json
- tests/unit/package_managers/test_npm.py
> add sbom properties for npm dev and bundled deps

- .github/dependabot.yml
- Containerfile
- js-deps/package-lock.json
- js-deps/package.json
> Install yarn v3 using corepack

- cachi2/core/checksum.py
- cachi2/core/models/input.py
- cachi2/core/package_managers/pip.py
- pyproject.toml
- requirements-extras.txt
- requirements.txt
- tests/integration/test_data/pip_e2e_test/bom.json
- tests/integration/test_data/pip_multiple/bom.json
- tests/integration/test_data/pip_without_metadata/bom.json
- tests/unit/models/test_input.py
- tests/unit/package_managers/test_pip.py
- tests/unit/test_checksum.py
> pip wheels

- cachi2/core/models/input.py
- cachi2/core/package_managers/yarn/__init__.py
- cachi2/core/package_managers/yarn/locators.py
- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/project.py
- cachi2/core/package_managers/yarn/resolver.py
- cachi2/core/package_managers/yarn/utils.py
This is an outline of how the code to resolve Yarn will look like. The goals we're aiming for are filing smaller and more focused implementation stories, being able to work on them in parallel and to agree upon a general direction on how the code should look like.
I think it's important to emphasize the code here is meant as a general guideline, and that the person that is implementing the separate stories is free to change whatever he/she wants from it.
Some design principles I tried to follow:
- Offload the main logic to functions, use model classes only to represent the relevant data and offer minor utility methods. (anemic models, as opposed to domain rich models)
- Keep the models immutable whenever possible
- Try to keep the functions small and focused
- Try to make use of Python …
> Yarn high-level code

- cachi2/core/package_managers/yarn/locators.py
- tests/unit/package_managers/yarn/test_locators.py
> Parse Yarnberry locators

- cachi2/core/package_managers/yarn/main.py
- cachi2/core/package_managers/yarn/project.py
- cachi2/core/package_managers/yarn/resolver.py
> Make Yarnberry a successful noop

- Makefile
- README.md
- tox.ini
> tox.ini: Fix Python environment factors

- README.md
> docs: update planned package managers

- .gitignore
Temporary files and ctags output.
- [-] Code coverage from testing does not decrease and new code is covered
- [-] Docs updated (if applicable)
- [-] Docs links in the code are still valid (if docs were updated) …
> misc: .gitignore: Add Vim-related files to .gitignore

- README.md
- cachi2/core/models/input.py
- cachi2/core/package_managers/bundler/__init__.py
- cachi2/core/package_managers/bundler/main.py
- cachi2/core/resolver.py
- tests/unit/models/test_input.py
- tests/unit/test_cli.py
> Add bundler to dev package managers

- pyproject.toml
> mypy improvements

- cachi2/core/resolver.py
- tests/unit/test_resolver.py
> Use temporary directory when resolving each package manager

- cachi2/core/package_managers/cargo/main.py
> cargo: Hide .cargo/config.toml before prefetching

- cachi2/core/resolver.py
- tests/unit/test_resolver.py
See individual commit messages for detailed explanations.
> core: resolver: Fix how project files paths are updated

- hermeto/interface/cli.py
- tests/integration/test_data/legacy_entrypoint_e2e_test/.build-config.yaml
- tests/integration/test_data/legacy_entrypoint_e2e_test/bom.json
- tests/integration/test_data/legacy_entrypoint_e2e_test/container/Containerfile
- tests/integration/test_legacy.py
- tests/integration/utils.py
See the last commit for more details. The last commit is supposed to be reverted in the future when we ditch the legacy entrypoint.
> [tests] [integration] Introduce an integration test for the legacy entrypoint - cachi2

- .github/workflows/docs.yaml
- README.md
- docs/generic.md
- docs/gomod.md
- docs/npm.md
- docs/pip.md
- docs/usage.md
- docs/yarn.md
- docs/yarn_classic.md
> Finalize hermeto website

- hermeto/core/package_managers/yarn_classic/main.py
- tests/unit/package_managers/yarn_classic/test_main.py
> Handle Yarn 1.x offline mirror race condition

- hermeto/core/package_managers/pip.py
- tests/unit/package_managers/test_pip.py
> Allow URLs with .whl file extension when wheels are allowed

- hermeto/core/models/property_semantics.py
- hermeto/core/package_managers/rpm/main.py
- tests/integration/test_data/rpm_e2e_modularity/bom.json
> Add RPM modularity label

- docs/generic.md
- docs/gomod.md
- docs/npm.md
- docs/pip.md
- docs/rpm.md
- docs/yarn.md
- docs/yarn_classic.md
- mkdocs.yml
> GitHub page final tweaks

- hermeto/core/package_managers/bundler/gem_models.py
- hermeto/core/package_managers/bundler/parser.py
- tests/unit/package_managers/bundler/test_main.py
- tests/unit/package_managers/bundler/test_parser.py
Noticed by accident when reviewing https://github.com/hermetoproject/hermeto/pull/1027
> bundler: Extract pydantic model definitions from the parser module

- README.md
- hermeto/core/package_managers/gomod.py
> Update gomod version to 1.25

- hermeto/core/checksum.py
- hermeto/core/package_managers/general.py
- hermeto/core/package_managers/gomod.py
- hermeto/core/package_managers/pip/main.py
- hermeto/core/package_managers/yarn/utils.py
- hermeto/core/rooted_path.py
- hermeto/core/scm.py
- hermeto/core/type_aliases.py
- tests/common_utils/__init__.py
- tests/integration/container_engine.py
- tests/integration/utils.py
- tests/unit/conftest.py
- tests/unit/package_managers/test_general.py
Motivated by a review comment in https://github.com/hermetoproject/hermeto/pull/1111
> Move some typing aliases to a new dedicated module
